[package]
name = "popsicle-ui"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "USB Flasher"
repository = "https://github.com/pop-os/popsicle"

[dependencies]
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
open = "5.3.2"
rust-embed = "8.8.0"
tokio = { version = "1.48.0", features = ["full"] }

atomic = "0.6.0"
anyhow = "1.0.79"
bytemuck = "1.14.0"
bytesize = "1.3.0"
cascade = "1.0.1"
crossbeam-channel = "0.5.10"
dbus = "0.9.7"
dbus-udisks2 = { git = "https://github.com/pop-os/dbus-udisks2" }
digest = "0.10.7"
futures = "0.3.30"
hex-view = "0.1.3"
iso9660 = { git = "https://github.com/ids1024/iso9660-rs" }
libc = "0.2.151"
md-5 = "0.10.6"
popsicle = { path = ".." }
pwd = "1.4.0"
sha2 = "0.10.8"
sha-1 = { version = "0.10.1", features = ["asm"] }
once_cell = "1.19.0"
blake2 = "0.10.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
xdgen = "0.1"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
# Remove features if not needed.
features = [
    # About widget for the app
    "about",
    # On app startup, focuses an existing instance if the app is already open
    "single-instance",
    # Markdown widget
    "markdown",
    # QR code widget
    "qr_code",
    # GPU-accelerated rendering
    "wgpu",
    # xdg portal dialogs on Linux
    "xdg-portal"
]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
