name: Flatpak
on: [push, pull_request]
jobs:
  flatpak:
    runs-on: ubuntu-latest

    container:
      image: flatpak/flatpak-github-actions:gnome-42
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        dnf -y install docker
      if: ${{ matrix.arch == 'aarch64' }}

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
      if: ${{ matrix.arch == 'aarch64' }}

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: Popsicle.flatpak
        manifest-path: com.system76.Popsicle.json
        cache-key: "flatpak-builder-${{ github.sha }}"
        arch: ${{ matrix.arch }}
